services:
  - type: web
    name: kino-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: DB_PATH
        value: kino_bot.db
